### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by MirjamOdile** [MirjamOdile/babyCARDS#2]
- [ ]  Write brief summary of the purpose of these classifiers
- [ ] Add information on the time frame of the documents
- [ ] Add instructions on usage (required data format and example code)
